### ISSUE TITLE
module 'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by R-N** [kakshay21/verify_email#36]
I ran the example on Google Colaboratory (Python 3.6.9, only installing this package):

```
from verify_email import verify_email
verify_email("asdf@gmail.com")
```

And I get this error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-7-74bd4e6e4343> in <module>()
      1 from verify_email import verify_email
----> 2 verify_email("asdf@gmail.com")

/usr/local/lib/python3.6/dist-packages/verify_email/verify_email.py in verify_email(emails, timeout, verify, debug)
     84 
     85     for email in emails:
---> 86         resp = asyncio.run(_verify_email(email, timeout, verify, debug))
     87         result.append(resp)
     88 

AttributeError: module 'asyncio' has no attribute 'run'
```

**Comment by kakshay21** [comment]
Hi @R-N 
`asyncio.run` is introduced in [python 3.7](https://docs.python.org/3/library/asyncio-task.html#asyncio.run)
If there is any issue in upgrading to py 3.7 then I would recommend you to use
`asyncio.loop.run_until_complete` instead of `asyncio.run`
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_until_complete

See for more details: https://stackoverflow.com/questions/52796630/python3-6-attributeerror-module-asyncio-has-no-attribute-run

**Comment by kakshay21** [comment]
Sadly, This package only supports Python 3.7+
https://github.com/kakshay21/verify_email#compatibility

**Comment by R-N** [comment]
> Sadly, This package only supports Python 3.7+
> https://github.com/kakshay21/verify_email#compatibility

My bad. Should've checked version requirement first.

Thank you for your quick response
